services:
    david63.resetpostcount.admin.controller:
        class: david63\resetpostcount\controller\admin_controller
        arguments:
            - @config
            - @request
            - @dbal.conn
            - @template
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%			
